package com.twosmall.constellation;

import javax.lang.model.element.VariableElement;

/**
 * @author gep
 * @description 代码千万行, 注释第一行;编程不规范,同事两行泪;
 * @date 2019-04-28 10:16
 */
public class Test {

    public static void main(String[] args) {
        System.out.println(subString3());
    }

    public static String subString(){
        String text = "1、相约而坐，相对无言。</p><p>　　2、我说，在看不到你的时候，就是我最寂寞的时候。</p><p>　　3、下辈子我们还在一起，你不来，我不老。</p><p>　　4、有一种终生配偶制的两栖动物叫松果蜥。</p><p>　　5、喜欢是乍见之欢，爱是久处不厌。</p><p>　　6、万千繁华不复你笑靥如花，似水流年。</p><p>　　7、在所有过去与将来，所有怀念和值得期待的景色里，我只喜欢你。</p><p>　　8、如果哪天我想环游世界了，我可以围着你转一圈吗？</p><p>　　9、能不能把我们的革命友谊再升华一下。</p><p>　　10、你的名字只有两个字，虽构不成一句话，但已经装满了我的心。</p><p>　　11、因为你，每天都是情人节。</p><p>　　12、我爱你，非常非常爱。很多年后我对很多人说过这句话，却再没有后面那五个字。</p><p>　　13、妹子，帮个忙，我爸妈想要个儿媳妇！</p><p>　　14、how you doing.</p><p>　　15、等我一下，我先洗个头再爱你。</p><p>　　16、如她伤你心，如她说别离，如果未嫌弃，我即奔向你。</p><p>　　17、右手敬礼，左手牵你。</p><p>　　18、别人眼中恶魔的你，却是我心中的天使。</p><p>　　19、今夜の月は綺麗だな。</p><p>　　20、我想要的很简单，你在，我在，时光还在。</p><p>　　21、山是水的故事，云是风的故事，你是我的故事。</p><p>　　22、来，抱抱！</p><p>　　23、遐想今日温柔，温柔于日后遐想：风雨执手，蹒跚而行。</p><p>　　24、愿意我开飞机送你一程吗？</p><p>　　25、希望人生是：十万首MP3、一百万张jpg、一千万公里和一个你。</p><p>　　26、就这样爱上了一首歌，一遍遍循环，听着歌词间的你我，傻笑着《情非得已》。</p><p>　　27、你是我命中的---在劫难逃。</p><p>　　28、我不喜欢这世界，我只喜欢你，喜欢有你的世界。</p><p>　　29、只有自己跟自己过得太久了的人才会渴望爱情，也才有资格获得爱情。</p><p>　　30、终有一天你我的距离将为负。</p><p>　　31、想象你，想像你，想你。</p><p>　　32、我愿意守护你所有的孤独。</p><p>　　33、只有和你在一起的时候，才不会去羡慕别人。</p><p>　　34、你怕，我怕，我还没说怕什么呢，关于你的所有，我都怕。</p><p>　　35、与你相遇，如入梦中，从此不愿醒矣。</p><p>　　36、校园卡给你，随便刷（总裁脸）。</p><p>　　37、选好化妆水乳液隔离霜眉粉口红眼线笔卧蚕笔以后，给你化好陪我出去吃饭吧！</p><p>　　38、11点11分，故意找你，只是没说出那句，其实我想你。</p><p>　　39、你还想要一个妈妈嘛，我把我的妈妈分给你。</p><p>　　40、你这么针对我，是不是想睡我。</p><p>　　41、我喜欢矮穷矬，矮了我可以低头，穷了我可以养他，矬的话可以对我一心一意。</p><p>　　42、来到人世间蹉跎几十年，只为望你回眸一眼。</p><p>　　43、你有地图吗，我在你的眼睛里迷路了。</p><p>　　44、我以为开学前见你一面，到学校后就不会想你。</p><p>　　45、你还小，我不忍心跟你谈恋爱。</p><p>　　46、我希望在我们以后的生活中都因为拥有彼此而快乐无边。</p><p>　　47、我每天偷拍你一張照片，等到妳60歲的時候，我再一張張翻開給你看。</p><p>　　48、你别哭，哭了我想笑。</p><p>　　49、流动在阳光和虚无间的我爱瑶。</p><p>　　50、从你的世界路过，我是那个偷影子的人。虽然无声告白，只愿你让我留在你身边。</p><p>　　51、以后我在楼下等你的时候你要快点，你们宿舍楼前的梧桐树都被我抠的没皮了。</p><p>　　52、你正在阅读我想你的声音。</p><p>　　53、我单身，自信帅，就酱紫。</p><p>　　54、我讨厌一切让我上瘾的东西除了你。</p><p>　　55、我送你一支口红，你要每天还我一点。</p><p>　　56、以后想在哪儿工作？……让我想想哈……在有你的地方。</p><p>　　57、说不喜欢你都是四月的谎言。</p><p>　　58、对不起，我明知道会这样 ，还是忍不住靠近你。</p><p>　　59、巧哎，看到这个比赛就想到你了。</p><p>　　60、微博有什么好玩的？哪有我好玩？</p><p>　　61、我以为开学前见你一面，回到学校的时候就不会再想你……</p><p>　　62、至少现在，你过得很好，这就够了。</p><p>　　63、爱情是没有国界的哈。</p><p>　　64、你总是能让我带着每天的晚安把梦做到最感动。</p><p>　　65、风这么大要多出门。万一吹到美女怀里，像我这样不要脸，肯定是赖着不动的。</p><p>　　66、停止思念，从来没有，一刻也没有。</p><p>　　67、所爱隔山海，山海不可平。</p><p>　　68、异地算什么，之前四年都过来了，还怕这四年？</p><p>　　69、小心翼翼地拉着你的手，在心里早就和你过完了一生。</p><p>　　70、你存在的本身，便是我的神迹。</p><p>　　71、Love=you +me+future children.</p><p>　　72、不许动，打劫，把你的心给我。</p><p>　　73、男：我已经完成领略世界风采的梦想。女：为什么？男：因为你就是我的世界。</p><p>　　74、我如今的气质里，藏着你走过的路，放着你唱过的歌，还有我深深喜欢着的你。</p><p>　　75、雪花来了，我的心还空着，你来吗？</p><p>　　76、与你相见，是我最美的相遇。</p><p>　　77、在春风起时你来到我的身边，我们一起度过人生的每一个季节。</p><p>　　78、我想和你虚度时光。</p><p>　　79、你回眸一笑，我愿为你画工图，虐高数，刷大物，一起飞过C++。</p><p>　　80、如果哪一天我想环游世界了，我可以围着你转一圈吗？</p><p>";
        String replace = text.replace("</p><p>", "");
        replace = replace.replaceAll("\\d+", "");
        replace = replace.replace("、", "\n");
        return replace;
    }

    public static String subString1(){
        String text = "1、我想要的很简单，时光还在，你还在。";
        String replace = text.replace("\n", "");
        replace = replace.replaceAll("\\d+", "");
        replace = replace.replace("、", "\n");
        return replace;
    }
    public static String subString2(){
        String text = "1.我的运气只到遇见你，接下来的，就要自己努力了。2.我有几千万里的山光相与你说，这沿途的星辰也想粒粒分明摘取下来交由你，你可不可以等我。3.如果你过得不幸福，我所做的一切才是徒劳。——东野圭吾4.“你为什么那么喜欢落日？”“因为它像极了我喜欢你的心……”“嗯？”“就算会一点一点沉下去，明天照样会升起。”——《德卡先生的信箱》5.我为的是我的心。——《石头记》6.“有一句话，我只问一次，以后都不会再问了，为什么会是我？”“答案很长，我准备用一生来回答，你准备好要听了吗？”——梁思成&林徽因7.在遇到她之前，我从未想过要结婚。和她在一起这么多年，我也从未想过娶别的女人。——钱钟书&杨绛8.你站在桥上看风景，看风景的人在桥上看你。明月装饰了你的窗子，你却装饰了别人的梦。——卞之琳&张充和9.我寄你的信，总要送往邮局，不喜欢放在街边的绿色邮筒中，我总疑心那里会慢一点。——鲁迅&许广平10.珍簟凉风著，瑶琴寄恨生。嵇君懒书札，底物慰秋情。——鱼幼薇&温庭筠11.言与司合,安上已脱,芝芙草拔。——李清照&赵明诚12.“你最可爱”，我说时来不及思索，而思索之后，还是这样说。——普希金13.“你会不爱我吗？”“不爱你？不会。爱你就像爱生命。”14.春水初生，春林初盛，春风十里，不如你。——冯唐15.我实在喜欢你那一身诗劲，我爱你像爱一首诗一样。——朱生豪16.我愿意舍弃一切，以想念你终此一生。——朱生豪17.静下来想你，觉得一切都美好得不可思议。——王小波18.你不在手边，手一直想你。——冯唐19.风和日暖，令人愿意永远活下去。——朱生豪20.今天起来看见太阳光，心里有一点高兴。——王小波\n" +
                "\n" +
                "\n" +
                "26.后海有树的院子，夏代有工的玉，此时此刻的云，二十来岁的你。——冯唐《可遇不可求的事》27.我爱他，是因为他像爱情本身该有的样子。——王尔德28.你问我爱你值不值得，其实你应该知道，爱就是不问值不值得。——张爱玲29.我要用尽我的万种风情，让你将来任何不和我在一起的时候，内心都无法安宁。——冯唐30.好多年了，你一直在我的伤口幽居。我放下过天地，从未放下过你。——仓央嘉措31.我这辈子走过很多的路，行过很多地方的桥，看过很多次数的云，喝过很多种类的酒，却只爱过一个正当年龄的人。——沈从文32.从前日色变得慢，车，马，邮件都慢。一生只够爱一个人。——木心33.你再不来，我要下雪了。——木心34.海底月是天上月，眼前人是心上人。向来心是看客心，奈何人是剧中人。——张爱玲35.你以为我刀枪不入，我以为你百毒不侵。——徐志摩36.为你，千千万万遍。——《追风筝的人》37.醒来觉得甚是爱你。——朱生豪《朱生豪情书》38.我遇见你，我记得你，这座城市天生就适合谈恋爱，你天生就适合我的灵魂。——《情人》39.你眉目笑语使我病了一场，热势退尽，还我寂寞的健康。——木心40.若深情不能对等，愿爱得更多的人是我。——奥登41.自从我们相遇，你是我白天黑夜不落的星。——莱蒙托夫42.我一天一天明白你的平凡，同时却一天一天愈更加深切地爱你。你如照镜子，你不会我看得见你特别美好的所在，但是你如走到我的心里来时，你一定能知道自己是怎样好法。——朱生豪43.在我贫瘠的土地上你是我最后的玫瑰。——聂鲁达44.草在结它的种子，风在摇它的叶子，我们站着不说话，就十分美好。——顾城45.我的心是旷野的鸟，在你的眼里找到了天空。——泰戈尔46.在青山绿水之间，我想牵你的手，走过这座桥，桥上是绿叶红花，桥下是流水人家，桥的那头是青丝，桥的这头是白发。——沈从文\n" +
                "\n" +
                "\n" +
                "月亮照回湖心，野鹤奔向闲云，我步入你。——仓央嘉措我住长江头，君住长江尾，日日思君不见君，共饮长江水。此水几时休，此恨几时已。只愿君心似我心，定不负相思意。——李之仪《卜算子》我把我的整个灵魂都给你，连同它的怪癖，耍小脾气，忽明忽暗，一千八百种坏毛病。它真讨厌，只有一点好，爱你。——王小波《爱你就像爱生命》因为你，我愿意成为一个更好的人，不想成为你的包袱，因此发奋努力，只是为了想要证明我足以与你相配。——宫崎骏《侧耳倾听》你的过去我不愿过问，那是你的事情。你的未来我希望我能参与，那是我的荣幸。——《神探夏洛克》我只有一点点的坏，小小的坏而已，最近我连柿子都没有偷了。上次经过好大一片橘子林，我好想偷几个，一想到你不喜欢，我连一个都没有摘呢。——《还珠格格》世界上有那么多城镇，城镇中有那么多酒馆，他却走进了我的。——《卡萨布兰卡》我，等着你。相信有一天你会出现抚摸我的头，夸奖我。时间流逝，我在守着爱你的那份忠诚。——《狼族少年》是你让我一直远离那无际的深渊。——《冷山》刚刚好，看见你幸福的样子，于是幸福着你的幸福。——《南境以南太阳以西》若深情不能对等，愿爱得更多的人是我。If equal affection cannot be,let the more loving one be me.与君初相识，犹似故人归。天涯明月新，朝暮最相思。我曾踏月来，只因你在山中。——席慕蓉《山月》南有乔木，不可休思，汉有游女，不可求思。——《诗经-汉广》我是如此的拙于表达，我所经历的时间和万物，真正算作美好的——并不多，所以才会对你如此珍而重之。今夜我不关心人类，我只想你。——海子其实你不喜欢我，我也不会死。但是如果你肯喜欢我，我一定会非常非常勇敢的活下去。";
        String replace = text.replace("\n", "");
        replace = replace.replaceAll("\\d+", "");
        replace = replace.replace(".", "\n");
        return replace;
    }

    public static String subString3 (){
        String str = "insert into gerp_teast set content = \"你最可爱，我说时来不及思索，但思索之后，还是这样说。\";\n" +
                "insert into gerp_teast set content = \"我觉得你太自恋了，说实话就长成你这样，选美比赛最多拿前三。\";\n" +
                "insert into gerp_teast set content = \"你为什么这么庸俗，老是发自拍，害我看了好几遍，手都酸了。\";\n" +
                "insert into gerp_teast set content = \"我发现你不适合谈恋爱，适合结婚。\";\n" +
                "insert into gerp_teast set content = \"这世界就是个巨大的娃娃机，我站在橱窗旁边，只想要你。\";\n" +
                "insert into gerp_teast set content = \"你为什么老是找我聊天，是不是喜欢我。不是的话，我再想想办法。\";\n" +
                "insert into gerp_teast set content = \"我发现你是个照骗，因为本人比照片好看多了。\";\n" +
                "insert into gerp_teast set content = \"愿意跟我体验一下不单身的感觉吗?我骄傲了十几年看见你我就怂了。\";\n" +
                "insert into gerp_teast set content = \"你吃东西的样子真可爱，是练过吗?\";\n" +
                "insert into gerp_teast set content = \"你的血型是方型的吗?要不为什么你长的这么正。\";\n" +
                "insert into gerp_teast set content = \"你比较喜欢猫还是狗，猫：喵;狗：汪汪。\";\n" +
                "insert into gerp_teast set content = \"你有男朋友吗?没有的话想不想有一个，有的话要不要换一个，不换的话介意不介意多一个。\";\n" +
                "insert into gerp_teast set content = \"无论什么时候，女人不喜欢男人博爱，只撩一个妹子或者你让妹子知道，你只撩她一个。\";\n" +
                "insert into gerp_teast set content = \"不论你多厉害，千万不要去撩人家的女朋友。挖墙脚有风险，小心墙压下来砸死你，这是忠告。\";\n" +
                "insert into gerp_teast set content = \"长的丑的撩妹当然需要套路，如果你长得帅，你只需要套。\";\n" +
                "insert into gerp_teast set content = \"女人永远无法拒绝和他彻夜长谈的男人！过了一夜，感觉就是翻了一页！\";\n" +
                "insert into gerp_teast set content = \"基本上所有的女人都喜欢男人正经中带点不正经，但这种不正经的前提是不影响正经，嗯，没错就是说，你要适当的耍流氓！\";\n" +
                "insert into gerp_teast set content = \"跟我在一起让我照顾你，你爱谁无所谓。\";\n" +
                "insert into gerp_teast set content = \"你不陪你女朋友吗?我哪有什么女朋友。哦?你不是说你一直有个女神吗?我不是正在跟她聊天吗?\";\n" +
                "insert into gerp_teast set content = \"我昨晚梦见你了，不知是你想我了还是我想你了。\";\n" +
                "insert into gerp_teast set content = \"你让我道歉，还是让我告白。\";\n" +
                "insert into gerp_teast set content = \"别人爱你只是想和你上床，我不一样，沙发，厨房，都可以。\";\n" +
                "insert into gerp_teast set content = \"我想升华一下我们纯洁的革命感情。\";\n" +
                "insert into gerp_teast set content = \"在我眼里你特别好看，从眼睫毛到头皮屑都好看的那种好看。\";\n" +
                "insert into gerp_teast set content = \"情书是我抄的，但喜欢你是真的。 \";\n" +
                "insert into gerp_teast set content = \"玫瑰是我偷的，但我爱你是真的。 \";\n" +
                "insert into gerp_teast set content = \"最喜欢睡觉和你 简称睡你。 \";\n" +
                "insert into gerp_teast set content = \"喜欢吃桔子 桔子汁不行 桔子糖不行 就像我 不是你不行。 \";\n" +
                "insert into gerp_teast set content = \"奇迹就留给别人吧，我有你了.' \";\n" +
                "insert into gerp_teast set content = \"你问我有多喜欢你 我也说不出来 我心里明白 我宁愿跟你吵 也不愿意去爱别人。 \";\n" +
                "insert into gerp_teast set content = \"不是我执着，而是伱值得。 \";\n" +
                "insert into gerp_teast set content = \"喜欢你就好像太阳不会放弃天空。 \";\n" +
                "insert into gerp_teast set content = \"我也害怕闹别扭时有人乘虚而入讨你欢心。 \";\n" +
                "insert into gerp_teast set content = \"比起天黑和鬼，我更害怕你心酸皱眉。 \";\n" +
                "insert into gerp_teast set content = \"你闺蜜的事与我无关，你的事，我不会让你有事。 \";\n" +
                "insert into gerp_teast set content = \"我都舍不得欺负的人，哪能让别人欺负？ \";\n" +
                "insert into gerp_teast set content = \"在有生的瞬间能遇到你，竟花光所有运气。 \";\n" +
                "insert into gerp_teast set content = \"晚安这么滥情，但我只想说给你听。 \";\n" +
                "insert into gerp_teast set content = \"牵着我的手，闭着眼睛走你也不会迷路。 \";\n" +
                "insert into gerp_teast set content = \"我只是喜欢你，我没有恶意。 \";\n" +
                "insert into gerp_teast set content = \"除了喜欢你 没别的毛病。 \";\n" +
                "insert into gerp_teast set content = \"你陪着我的时候我没羡慕过任何人。 \";\n" +
                "insert into gerp_teast set content = \"人一生会遇到约2920万人 两个人相爱的概率是0.000049 所以你不爱我 我并不怪你。 \";\n" +
                "insert into gerp_teast set content = \"你不理我的时候我就觉得你在好好学习，准备以后养我。 \";\n" +
                "insert into gerp_teast set content = \"世界上哪来的那么多一见如故 无话不谈不过是因为那个人喜欢你所以你说的话题他都感兴趣你叫他听的歌他都觉得有意义你说的电影他都觉得有深意你口中的风景他都觉得好美丽不过是因为他喜欢你。 \";\n" +
                "insert into gerp_teast set content = \"请问你有女朋友吗？没有，好，现在你已经有了。 \";\n" +
                "insert into gerp_teast set content = \"我拿余生与你举案齐眉 请别让我皱眉也请不要让我心如死灰。 \";\n" +
                "insert into gerp_teast set content = \"你扬着头大笑的样子真的好喜欢 你和不三不四的人混在一起的样子真的好讨厌\";\n" +
                "insert into gerp_teast set content = \"我家的狗挺喜欢你的 随我。 \";\n" +
                "insert into gerp_teast set content = \"你是年少的欢喜，我想把这句话反过来告诉你。 \";\n" +
                "insert into gerp_teast set content = \"西红柿和番茄 马铃薯和土豆 我喜欢的人和你。 \";\n" +
                "insert into gerp_teast set content = \"你生日几号 干嘛告诉你 我密码忘了。 \";\n" +
                "insert into gerp_teast set content = \"想了又想 最后还是决定告诉你我长话短说：我喜欢你。 \";\n" +
                "insert into gerp_teast set content = \"你要我说多难堪我根本不想分开。 \";\n" +
                "insert into gerp_teast set content = \"我不是话唠，只是憋太久了终于等到你。 \";\n" +
                "insert into gerp_teast set content = \"篱笆外的猫不再受宠 有些事我懂。\";\n" +
                "insert into gerp_teast set content = \"我想要的很简单，时光还在，你还在。　　\";\n" +
                "insert into gerp_teast set content = \"想和你喝酒是假，想醉你怀里是真。　　\";\n" +
                "insert into gerp_teast set content = \"傻笑不是与生俱来的，而是由我爱上你的那一刻开始的。　　\";\n" +
                "insert into gerp_teast set content = \"你这么针对我，是不是想睡我。　　\";\n" +
                "insert into gerp_teast set content = \"假如你是一棵仙人掌，我也愿意忍受所有的疼痛来抱着你。　　\";\n" +
                "insert into gerp_teast set content = \"假如可以的话，我愿意花去生命中的每一分每一秒，陪着你。　　\";\n" +
                "insert into gerp_teast set content = \"你是年少的欢喜，我想把这句话反过来告诉你。　　\";\n" +
                "insert into gerp_teast set content = \"你还想要一个妈妈嘛，我把我的妈妈分给你。　　\";\n" +
                "insert into gerp_teast set content = \"谢谢你的微笑，曾经慌乱过我的年华。　　\";\n" +
                "insert into gerp_teast set content = \"等我一下，我先洗个头再爱你。　　\";\n" +
                "insert into gerp_teast set content = \"异地算什么，之前四年都过来了，还怕这四年?　　\";\n" +
                "insert into gerp_teast set content = \"我和我的猫都很想你，可是我没有猫，也没有你。　　\";\n" +
                "insert into gerp_teast set content = \"你知道我最珍惜什么吗，就是这句话的第一个字。　　\";\n" +
                "insert into gerp_teast set content = \"我仿佛从不懂什么是爱，直到，我遇见你。　　\";\n" +
                "insert into gerp_teast set content = \"我明白你会来，所以我等。　　\";\n" +
                "insert into gerp_teast set content = \"听过一个故事没有?弓在箭射出之前低声对箭说：你的自由是我的。　　\";\n" +
                "insert into gerp_teast set content = \"妹子，帮个忙，我爸妈想要个儿媳妇!　　\";\n" +
                "insert into gerp_teast set content = \"幸福的秘诀是得到自由，而自由的秘诀是勇气。　　\";\n" +
                "insert into gerp_teast set content = \"我都舍不得欺负的人，哪能让别人欺负?　　\";\n" +
                "insert into gerp_teast set content = \"看着微笑的你，突然发现，我真是世界上最幸福的人。　　\";\n" +
                "insert into gerp_teast set content = \"你的名字只有两个字，虽构不成一句话，但已经装满了我的心。　　\";\n" +
                "insert into gerp_teast set content = \"你烦我，你再烦我，你就娶我。　　\";\n" +
                "insert into gerp_teast set content = \"人生不长，该珍惜就别保持不近不远，我只想再抱你紧一点。　　\";\n" +
                "insert into gerp_teast set content = \"只有自己跟自己过得太久了的人才会渴望爱情，也才有资格获得爱情。　　\";\n" +
                "insert into gerp_teast set content = \"你别难过，风筝有风，海豚有海，你还有我。　　\";\n" +
                "insert into gerp_teast set content = \"看过怦然心动吗?所以你懂我对你感觉?怦然心动。　　\";\n" +
                "insert into gerp_teast set content = \"雪花来了，我的心还空着，你来吗?　　\";\n" +
                "insert into gerp_teast set content = \"你在的时候，你是一切;你不在的时候，一切是你!　　\";\n" +
                "insert into gerp_teast set content = \"我可能缺席了你的过去，但我希望你不要缺席我的未来。　　\";\n" +
                "insert into gerp_teast set content = \"你还小，我不忍心跟你谈恋爱。　　\";\n" +
                "insert into gerp_teast set content = \"再累，再苦，再疼，也只是为了你能喜欢我而已。　　\";\n" +
                "insert into gerp_teast set content = \"世界上最温暖的两个字是从你口中说出的晚安。　　\";\n" +
                "insert into gerp_teast set content = \"没有你的生活如同行尸走肉般，一根烟，一杯酒，就这么无所谓下去。　　\";\n" +
                "insert into gerp_teast set content = \"如果你愿意，我就喜欢你，如果你不愿意，我就单相思，你愿意吗?　　\";\n" +
                "insert into gerp_teast set content = \"不是除了你，我就没人要了。只是除了你，我谁都不想要。　　\";\n" +
                "insert into gerp_teast set content = \"世上最浪漫和最自私的话就是：你是我一个人的。　　\";\n" +
                "insert into gerp_teast set content = \"如她伤你心，如她说别离，如果未嫌弃，我即奔向你。　　\";\n" +
                "insert into gerp_teast set content = \"给你讲个故事，这故事很长，所以我长话短说，我想你了。　　\";\n" +
                "insert into gerp_teast set content = \"能不能把我们的革命友谊再升华一下。　　\";\n" +
                "insert into gerp_teast set content = \"奇迹就留给别人吧，我有你了。　　\";\n" +
                "insert into gerp_teast set content = \"我以为开学前见你一面，到学校后就不会想你。　　\";\n" +
                "insert into gerp_teast set content = \"我希望在我们以后的生活中都因为拥有彼此而快乐无边。　　\";\n" +
                "insert into gerp_teast set content = \"下辈子我们还在一起，你不来，我不老。　　\";\n" +
                "insert into gerp_teast set content = \"你怕，我怕，我还没说怕什么呢，关于你的所有，我都怕。　　\";\n" +
                "insert into gerp_teast set content = \"与你相遇，如入梦中，从此不愿醒矣。　　\";\n" +
                "insert into gerp_teast set content = \"你的前半生没有我，那么就让我陪你走完后半生。　　\";\n" +
                "insert into gerp_teast set content = \"在认识你之后，我才发现自己可以这样情愿的付出。　　\";\n" +
                "insert into gerp_teast set content = \"不管你在乎不在乎我，我依旧会在乎你。　　\";\n" +
                "insert into gerp_teast set content = \"这世界上一共三种人，坏人，人妖，我的人。　　\";\n" +
                "insert into gerp_teast set content = \"遇见你，是我最美丽的意外。\";\n" +
                "insert into gerp_teast set content = \"如果你愿意，我就喜欢你，如果你不愿意，我就单相思，你愿意吗?\";\n" +
                "insert into gerp_teast set content = \"不是除了你，我就没人要了。只是除了你，我谁都不想要。\";\n" +
                "insert into gerp_teast set content = \"家常小菜，满汉全席都不是问题。\";\n" +
                "insert into gerp_teast set content = \"八块腹肌会修电梯，从不乱扔垃圾。\";\n" +
                "insert into gerp_teast set content = \"跟着我，别走丢。\";\n" +
                "insert into gerp_teast set content = \"我与世界只差一个你，因为是你，晚一点没关系。\";\n" +
                "insert into gerp_teast set content = \"最近我牙齿痛，因为常常晚上想你，那感觉太甜蜜了，会蛀牙。\";\n" +
                "insert into gerp_teast set content = \"我用尽了全部的运气，只为遇到你的那个瞬间，生命在那刻点亮。\";\n" +
                "insert into gerp_teast set content = \"和你一起，我不能保证你是最快乐的，但我一定是最幸福的哪个。\";\n" +
                "insert into gerp_teast set content = \"如果我们之间有步的距离，你只要跨出第步，那剩余的步就由我来走向你。\";\n" +
                "insert into gerp_teast set content = \"世界很大，我的心却很小，刚刚够放下你。可是卡住了，不能够再放你出去。\";\n" +
                "insert into gerp_teast set content = \"喜欢你，用打字很容易，用写的也很容易，别人说的也很容易，可是为什么当着你的面，我就是说不出来……\";\n" +
                "insert into gerp_teast set content = \"喜欢跟爱是不一样的，喜欢是荡秋千可以自得其乐不需别人的回应;爱是翘翘板需要一个人坐在对面与你互动贴近你内心的感觉，你是否愿意一直坐在我对面?\";\n" +
                "insert into gerp_teast set content = \"世界上最温暖的两个字是从你口中说出的晚安。\";\n" +
                "insert into gerp_teast set content = \"没有你的生活如同行尸走肉般，一根烟，一杯酒，就这么无所谓下去。\";\n" +
                "insert into gerp_teast set content = \"如果你愿意，我就喜欢你，如果你不愿意，我就单相思，你愿意吗?\";\n" +
                "insert into gerp_teast set content = \"不是除了你，我就没人要了。只是除了你，我谁都不想要。\";\n" +
                "insert into gerp_teast set content = \"我真的是太笨了，怎么啦！除了喜欢你，其它什么都做不好。\";\n" +
                "insert into gerp_teast set content = \"要是我和你生一个孩子你觉得他会是什么座？什么座？双子座？不，我们的杰作。\";\n" +
                "insert into gerp_teast set content = \"希望微风不燥 时光不老 你我都好。\";\n" +
                "insert into gerp_teast set content = \"小姐姐，小姐姐，你是什么座的啊？金牛座啊，你呢？我是…我是为你量身定做的。\";\n" +
                "insert into gerp_teast set content = \"我不要再抱怨生活了，为啥，我想要拥抱你。\";\n" +
                "insert into gerp_teast set content = \"你知道你和猴子有什么区别吗？不知道。猴子住在山洞里，你住在我心里。\";\n" +
                "insert into gerp_teast set content = \"我不小心把'我爱你'误发给你了。如果你接受那就贮存起来，如果你不接受，就把这三个字返发给我。\";\n" +
                "insert into gerp_teast set content = \"未来的日子，我想和你一房二人三餐四季。\";\n" +
                "insert into gerp_teast set content = \"你是我的今天，以及所有的明天。\";\n" +
                "insert into gerp_teast set content = \"我觉得你这个人不适合谈恋爱'为什么?'适合结婚。'\";\n" +
                "insert into gerp_teast set content = \"你上辈子一定是碳酸饮料吧，为什么我一看到你就能开心的冒泡。\";\n" +
                "insert into gerp_teast set content = \"我喜欢的女生 要个性十足，温柔贤惠，孝敬父母，不会乱发脾气，会跟我讲道理，会给我送礼物，会跟我撒娇，比我矮一点点，长头发的，如果有一双大眼睛那就完美了，可惜你只占了六个字：我喜欢的女生。\";\n" +
                "insert into gerp_teast set content = \"你能不能别老问我，你在干嘛？'我无时不刻都在想你。'\";\n" +
                "insert into gerp_teast set content = \"最近我牙齿痛，因为常常晚上想你，那感觉太甜蜜了，会蛀牙。\";\n" +
                "insert into gerp_teast set content = \"知道为什么你比我高嘛？为什么？因为上天都知道男生要向自己媳妇低头。\";\n" +
                "insert into gerp_teast set content = \"我有罪。什么？我正在你的芳心纵火。\";\n" +
                "insert into gerp_teast set content = \"甜有种方式：吃糖，蛋糕，还有每天次的想你。\";\n" +
                "insert into gerp_teast set content = \"我想你一定很忙，所以只用看前三个字就好。\";\n" +
                "insert into gerp_teast set content = \"见到你我就改吃素了，为什么？因为你是我的菜。\";\n" +
                "insert into gerp_teast set content = \"你说我们俩掉进河里会怎么样？冷死吧！我们不会有事，因为是坠入爱河。\";\n" +
                "insert into gerp_teast set content = \"你把手给我看看。（摊手）咦，你这，命里缺我啊！\";\n" +
                "insert into gerp_teast set content = \"小姐姐我可以向你问路吗？到哪里？到你心里。\";\n" +
                "insert into gerp_teast set content = \"请管好你的嘴。为什么?因为我会随时亲你。\";\n" +
                "insert into gerp_teast set content = \"你知道我姓什么？认识你之后我幸福。\";\n" +
                "insert into gerp_teast set content = \"我的手机被偷了？那你报警啊！好的，抱紧。\";\n" +
                "insert into gerp_teast set content = \"你夹娃娃很厉害吧。不厉害咋滴？那你怎么紧紧夹住我的心。\";\n" +
                "insert into gerp_teast set content = \"你喜不喜欢水？我喜欢它。恭喜你，你已经喜欢上%的我了。\";\n" +
                "insert into gerp_teast set content = \"我觉得你今天有点怪。 哪里怪？怪可爱的。\";\n" +
                "insert into gerp_teast set content = \"小姐姐，问你个问题 你问吧 情人节你跟谁过呢 不知道 你怎么知道我叫不知道呢\";\n" +
                "insert into gerp_teast set content = \"落叶归根 我归你 月逐江水 我逐你 鹤归孤山 我归你 八荒归元 我归你 春泥护花 我护你\";\n" +
                "insert into gerp_teast set content = \"你吃烧烤会先烤什么！先烤肉啊，我会先考虑你……\";\n" +
                "insert into gerp_teast set content = \"你喜欢你自己吗？喜欢呀！那我要做你一辈子的情敌。\";\n" +
                "insert into gerp_teast set content = \"我给你变个魔术，.......变完了，哪里变了？我变得更喜欢你了\";\n" +
                "insert into gerp_teast set content = \"我觉得我好花心，为什么？因为你的每个样子我都喜欢。\";\n" +
                "insert into gerp_teast set content = \"你这么可爱！被大风吹到我怀里，我是不会还的\";\n" +
                "insert into gerp_teast set content = \"我想在你那买块地。什么地？买你的死心塌地。\";\n" +
                "insert into gerp_teast set content = \"猜猜看我的心脏在哪边？在左边。错了，我的心在你那边。\";\n" +
                "insert into gerp_teast set content = \"你累不累？你在我脑子里跑了一天了。\";\n" +
                "insert into gerp_teast set content = \"你为什么要害我！我害你？害我那么喜欢你！\";\n" +
                "insert into gerp_teast set content = \"你可以做我的奥利奥吗？为什么？因为我想泡你！\";\n" +
                "insert into gerp_teast set content = \"你猜一下我是什么星座？不知道？我是什么都想为你做\";\n" +
                "insert into gerp_teast set content = \"你是兔子吧！怎么这么说？不然怎么一直在我的心上蹦跶。\";\n" +
                "insert into gerp_teast set content = \"你知道亲人眼里出什么吗？西施啊？不，出现你\";\n" +
                "insert into gerp_teast set content = \"我这个有个缺点，什么缺点，缺点你\";\n" +
                "insert into gerp_teast set content = \"莫文蔚的阴天，孙燕姿的雨天，周杰伦的晴天，都不如你和我聊天\";\n" +
                "insert into gerp_teast set content = \"你是哪里的啊？我是广州的，不，你是我的\";\n" +
                "insert into gerp_teast set content = \"你知道你爸妈有了你姐之后为什么还要你吗？为什么？给我的啊！！\";\n" +
                "insert into gerp_teast set content = \"对了，你多大了２５，我欠了你２５年陪伴\";\n" +
                "insert into gerp_teast set content = \"我喜欢你已经超过两分钟了，不能撤回了。\";\n" +
                "insert into gerp_teast set content = \"三十晚上的鞭炮再想，都没有我想想你那么想。\";\n" +
                "insert into gerp_teast set content = \"现在几点了？'点。'不，是我们幸福的起点。'\";\n" +
                "insert into gerp_teast set content = \"我想吃碗面'什么面？'你的心里面。'\";\n" +
                "insert into gerp_teast set content = \"我还是喜欢你，像小时候吃辣条，不看日期。\";\n" +
                "insert into gerp_teast set content = \"我觉得你好像一款游戏。'什么游戏？'我的世界。'\";\n" +
                "insert into gerp_teast set content = \"你的脸上有点东西。'有什么？'有点漂亮。'\";\n" +
                "insert into gerp_teast set content = \"听闻姑娘治家有方，鄙人余生愿闻其详。\";\n" +
                "insert into gerp_teast set content = \"我很能干但有一件事不会。'什么？'不会离开你。'\";\n" +
                "insert into gerp_teast set content = \"如果我丢了怎么办？报警就好了，什么？抱紧我就好了\";\n" +
                "insert into gerp_teast set content = \"你是我漫漫余生里斩钉截铁的梦想\";\n" +
                "insert into gerp_teast set content = \"想去有你的城市流浪，去你住的地方逛逛.\";\n" +
                "insert into gerp_teast set content = \"你的名字我的心事\";\n" +
                "insert into gerp_teast set content = \"向来桀骜不驯 为你车仰马翻\";\n" +
                "insert into gerp_teast set content = \"我喜欢你的眼睛，但更喜欢我的眼睛，因为我的眼里有你\";\n" +
                "insert into gerp_teast set content = \"清晨醒来你和阳光都在便是我想要的未来\";\n" +
                "insert into gerp_teast set content = \"我想你，一天比一天深，一天比一天频繁，还一天比一天更浓\";\n" +
                "insert into gerp_teast set content = \"我打算爱你很久很久，没有想要放弃的念头\";\n" +
                "insert into gerp_teast set content = \"你爸是小偷吧？为什么？他把星星偷来当做你的眼睛啊\";\n" +
                "insert into gerp_teast set content = \"愿我能陪你颠沛流离\";\n" +
                "insert into gerp_teast set content = \"南风知我意 白首不分离\";\n" +
                "insert into gerp_teast set content = \"没有诗和远方我只想要你\";\n" +
                "insert into gerp_teast set content = \"我爱你 没有技巧 真诚而又野蛮\";\n" +
                "insert into gerp_teast set content = \"喜欢你迷人的眼睛，思考的表情，动听的声音，我心里你就是唯一，已经没人可以代替\";\n" +
                "insert into gerp_teast set content = \"曾想过放下你 可想到你是世上唯一 心就一阵窒息\";\n" +
                "insert into gerp_teast set content = \"爱一个人是什么感觉，大概就是什么都介意却什么都原谅\";\n" +
                "insert into gerp_teast set content = \"幸福就是，猫吃鱼，狗吃肉，凹凸曼打小怪兽，我和你，手牵手，安安稳稳到白头\";\n" +
                "insert into gerp_teast set content = \"我想牵你的手，从心动，到古稀\";\n" +
                "insert into gerp_teast set content = \"我喜欢你，像你的眉眼不行，像你的脾气不行，不是你不行\";\n" +
                "insert into gerp_teast set content = \"你知道你适合穿什么衣服吗？漂亮的衣服！不，是被我征服。\";\n" +
                "insert into gerp_teast set content = \"你是朝露，是晚星，是我一切欢喜，我舔舐你的眼睛，未饮酒，已酩酊\";\n" +
                "insert into gerp_teast set content = \"你有多特别呢？万千人中走过，即便近视也能一眼望到你\";\n" +
                "insert into gerp_teast set content = \"世界这么大，我遇到了你 ，你也遇到了我，真好\";\n" +
                "insert into gerp_teast set content = \"从前车马很慢，书信很远，一生只够爱一人\";\n" +
                "insert into gerp_teast set content = \"海底月是天上月，眼前人是心上人\";\n" +
                "insert into gerp_teast set content = \"想做你的枕边书，怀中猫，还有意中人\";\n" +
                "insert into gerp_teast set content = \"三生有幸遇见你，纵使无缘亦不悔\";\n" +
                "insert into gerp_teast set content = \"遇见你之前，我尚是一张白纸，遇见你之后，我变成一叠情书\";\n" +
                "insert into gerp_teast set content = \"无论岁月怎样变迁，我都会记得你当年让我一眼动心的样子\";\n" +
                "insert into gerp_teast set content = \"假如这一生可以有次好运，我愿意把次都分给你，只留两次给自己，一次是遇见你，一次是永远陪你走下去\";\n" +
                "insert into gerp_teast set content = \"你闻到什么味道了吗？没有啊？怎么你一出来空气都是舔的了\";\n" +
                "insert into gerp_teast set content = \"十句搭讪 百句晚安 千句闲聊 万句废话，只为有一天在婚礼堂上听到一句我爱你\";\n" +
                "insert into gerp_teast set content = \"原谅我强烈的占有欲 我很小气因为太爱你 所以看谁都像情敌\";\n" +
                "insert into gerp_teast set content = \"晚是世界的晚，安是有你的安\";\n" +
                "insert into gerp_teast set content = \"深夜的习惯，除了熬夜还有想你\";\n" +
                "insert into gerp_teast set content = \"我遇见你很晚，但我会陪你很久\";\n" +
                "insert into gerp_teast set content = \"我斑斓如水的人生只为一个你.\";\n" +
                "insert into gerp_teast set content = \"此生我等你 没有因为 没有所以\";\n" +
                "insert into gerp_teast set content = \"愿你如阳光 明媚不忧伤\";\n" +
                "insert into gerp_teast set content = \"我希望拣到一片叶子 上面写满了你的名字\";\n" +
                "insert into gerp_teast set content = \"昨晚梦见你对我笑，一笑倾心\";\n" +
                "insert into gerp_teast set content = \"最喜欢睡觉和你 简称睡你。\";\n" +
                "insert into gerp_teast set content = \"喜欢吃桔子 桔子汁不行 桔子糖不行 就像我 不是你不行。\";\n" +
                "insert into gerp_teast set content = \"奇迹就留给别人吧，我有你了.'\";\n" +
                "insert into gerp_teast set content = \"你问我有多喜欢你 我也说不出来 我心里明白 我宁愿跟你吵 也不愿意去爱别人。\";\n" +
                "insert into gerp_teast set content = \"不是我执着，而是伱值得。\";\n" +
                "insert into gerp_teast set content = \"喜欢你就好像太阳不会放弃天空。\";\n" +
                "insert into gerp_teast set content = \"我也害怕闹别扭时有人乘虚而入讨你欢心。\";\n" +
                "insert into gerp_teast set content = \"比起天黑和鬼，我更害怕你心酸皱眉。\";\n" +
                "insert into gerp_teast set content = \"你闺蜜的事与我无关，你的事，我不会让你有事。\";\n" +
                "insert into gerp_teast set content = \"我都舍不得欺负的人，哪能让别人欺负？\";\n" +
                "insert into gerp_teast set content = \"在有生的瞬间能遇到你，竟花光所有运气。\";\n" +
                "insert into gerp_teast set content = \"晚安这么滥情，但我只想说给你听。\";\n" +
                "insert into gerp_teast set content = \"牵着我的手，闭着眼睛走你也不会迷路。\";\n" +
                "insert into gerp_teast set content = \"我只是喜欢你，我没有恶意。\";\n" +
                "insert into gerp_teast set content = \"春风十里 五十里 一百里 体测八百米 海底两万里 德芙巧克力 香草味八喜 可可布朗尼 榴莲菠萝蜜 芝士玉米粒 鸡汁土豆泥 黑椒牛里脊 黄焖辣子鸡 红烧排骨酱醋鱼 不如你 全都不如你'\";\n" +
                "insert into gerp_teast set content = \"除了喜欢你 没别的毛病。\";\n" +
                "insert into gerp_teast set content = \"你陪着我的时候我没羡慕过任何人。\";\n" +
                "insert into gerp_teast set content = \"人一生会遇到约万人 两个人相爱的概率是. 所以你不爱我 我并不怪你。\";\n" +
                "insert into gerp_teast set content = \"愿你迷路一生，还是走到我身旁。\";\n" +
                "insert into gerp_teast set content = \"你不理我的时候我就觉得你在好好学习，准备以后养我。\";\n" +
                "insert into gerp_teast set content = \"世界上哪来的那么多一见如故 无话不谈不过是因为那个人喜欢你所以你说的话题他都感兴趣你叫他听的歌他都觉得有意义你说的电影他都觉得有深意你口中的风景他都觉得好美丽不过是因为他喜欢你。\";\n" +
                "insert into gerp_teast set content = \"请问你有女朋友吗？没有，好，现在你已经有了。\";\n" +
                "insert into gerp_teast set content = \"我拿余生与你举案齐眉 请别让我皱眉也请不要让我心如死灰。\";\n" +
                "insert into gerp_teast set content = \"你扬着头大笑的样子真的好喜欢 你和不三不四的人混在一起的样子真的好讨厌'\";\n" +
                "insert into gerp_teast set content = \"我家的狗挺喜欢你的 随我。\";\n" +
                "insert into gerp_teast set content = \"你是年少的欢喜，我想把这句话反过来告诉你。\";\n" +
                "insert into gerp_teast set content = \"西红柿和番茄 马铃薯和土豆 我喜欢的人和你。\";\n" +
                "insert into gerp_teast set content = \"你生日几号 干嘛告诉你 我密码忘了。\";\n" +
                "insert into gerp_teast set content = \"想了又想 最后还是决定告诉你我长话短说：我喜欢你。\";\n" +
                "insert into gerp_teast set content = \"你要我说多难堪我根本不想分开。\";\n" +
                "insert into gerp_teast set content = \"我不是话唠，只是憋太久了终于等到你。\";\n" +
                "insert into gerp_teast set content = \"篱笆外的猫不再受宠 有些事我懂。\";\n" +
                "insert into gerp_teast set content = \"谢谢你的微笑，曾经慌乱过我的年华。\";\n" +
                "insert into gerp_teast set content = \"我见过千万人像你的发像你的眼但都不是你的脸。\";\n" +
                "insert into gerp_teast set content = \"我畏寒却偏爱冬天三分钟热度也曾紧拥你漫长许多年。\";\n" +
                "insert into gerp_teast set content = \"我喜欢春天的花夏天的树秋天的黄昏冬天的阳光和每天的你。\";\n" +
                "insert into gerp_teast set content = \"我真的很花心 喜欢每一个你。\";\n" +
                "insert into gerp_teast set content = \"不管你在乎不在乎我，我依旧会在乎你。\";\n" +
                "insert into gerp_teast set content = \"你不在 我也过得很好 可是这不代表你不重要。\";\n" +
                "insert into gerp_teast set content = \"你说你不相信任何人，不相信爱情要等，不相信我对你爱的够深，你却总固执的坚信着自己不适合谈恋爱，那我就用一生来陪你等 让你信爱情。\";\n" +
                "insert into gerp_teast set content = \"爱你很好 连风都知道 第一次心甘情愿不想逃。\";\n" +
                "insert into gerp_teast set content = \"我要购买你十年之后的出嫁权。\";\n" +
                "insert into gerp_teast set content = \"我可以亲你吗'不可以'我刚刚说了什么'我可以亲你吗'可以'\";\n" +
                "insert into gerp_teast set content = \"如果你觉得不开心的话，你就尽情的欺负我好了，反正我很喜欢你。\";\n" +
                "insert into gerp_teast set content = \"在我这块荒原上 你是最后一朵玫瑰。\";\n" +
                "insert into gerp_teast set content = \"喜欢不能太明显 不然不值钱。\";\n" +
                "insert into gerp_teast set content = \"我把一个人当做替代品了'谁？'和你长得很像的人'。\";\n" +
                "insert into gerp_teast set content = \"就算你长成你身份证照片那个样子 我也喜欢你啊。\";\n" +
                "insert into gerp_teast set content = \"四年之后我说喜欢你 你不要拒绝 好不好。\";\n" +
                "insert into gerp_teast set content = \"没错你家玻璃是我砸坏的怕你关了窗户听不到我在楼下喊我爱你。\";\n" +
                "insert into gerp_teast set content = \"你在我左胸第四根肋骨一寸往里的地方。听他们说那里是心脏。\";\n" +
                "insert into gerp_teast set content = \"下辈子你住我家隔壁好不好 我两青梅竹马两小无猜。\";\n" +
                "insert into gerp_teast set content = \"藏不住的感情 理直气壮就好了。\";\n" +
                "insert into gerp_teast set content = \"如果 1+2=2+1那么是否 i love you=you love me\";\n" +
                "insert into gerp_teast set content = \"听过一个故事没有？弓在箭射出之前低声对箭说：你的自由是我的.。\";\n" +
                "insert into gerp_teast set content = \"你应该喜欢一个让你笑的人 比如我'\";\n" +
                "insert into gerp_teast set content = \"等我能再勇敢一些 我就会义无反顾的来到你的身边。\";\n" +
                "insert into gerp_teast set content = \"Hey！我有大白兔，你愿不愿做我的英雄？\";\n" +
                "insert into gerp_teast set content = \"听不懂英文歌 可仍旧很痴迷 就像我从未了解你一样。完了，小编整理了这么久，累的不行不行的，说吧，你们要怎么谢我？可不可以送小编一双美丽的小花鞋，哈哈哈哈哈哈......\";\n" +
                "insert into gerp_teast set content = \"煎茶坐看梨门雨，诗书是你，风景也是你。\";\n" +
                "insert into gerp_teast set content = \"幸得识卿桃花面，自此阡陌多暖春。\";\n" +
                "insert into gerp_teast set content = \"只要你一直在我身边，其他东西不再重要。\";\n" +
                "insert into gerp_teast set content = \"只有和你在一起的时候，才不会去羡慕别人。\";\n" +
                "insert into gerp_teast set content = \"我有一个梦想，遇你，纤风，共夕阳。\";\n" +
                "insert into gerp_teast set content = \"你的名字只有三个字，虽构不成一句话，但已经装满了我的心。\";\n" +
                "insert into gerp_teast set content = \"你还小，我不忍心跟你谈恋爱。\";\n" +
                "insert into gerp_teast set content = \"再累，再苦，再疼，也只是为了你能喜欢我而已。\";\n" +
                "insert into gerp_teast set content = \"世界上最温暖的两个字是从你口中说出的晚安。\";\n" +
                "insert into gerp_teast set content = \"没有你的生活如同行尸走肉般，一根烟，一杯酒，就这么无所谓下去。\";\n" +
                "insert into gerp_teast set content = \"如果你愿意，我就喜欢你，如果你不愿意，我就单相思，你愿意吗？\";\n" +
                "insert into gerp_teast set content = \"不是除了你，我就没人要了。只是除了你，我谁都不想要。\";\n" +
                "insert into gerp_teast set content = \"你烦我，你再烦我，你就娶我。\";\n" +
                "insert into gerp_teast set content = \"人生不长，该珍惜就别保持不近不远，我只想再抱你紧一点。\";\n" +
                "insert into gerp_teast set content = \"只有自己跟自己过得太久了的人才会渴望爱情，也才有资格获得爱情。\";\n" +
                "insert into gerp_teast set content = \"你别难过，风筝有风，海豚有海，你还有我。\";\n" +
                "insert into gerp_teast set content = \"看过怦然心动吗？所以你懂我对你感觉？怦然心动。\";\n" +
                "insert into gerp_teast set content = \"雪花来了，我的心还空着，你来吗？\";\n" +
                "insert into gerp_teast set content = \"你在的时候，你是一切；你不在的时候，一切是你！\";\n" +
                "insert into gerp_teast set content = \"我可能缺席了你的过去，但我希望你不要缺席我的未来。\";\n" +
                "insert into gerp_teast set content = \"我是预言家，昨天验了你的身份，你是我女朋友\";\n" +
                "insert into gerp_teast set content = \"我脑袋里的西瓜籽可能是发芽了 不然怎么在觉得已经够喜欢你的时候还能喜欢你呀\";\n" +
                "insert into gerp_teast set content = \"晚什么安 我巴不得你想我想的夜不能寐\";\n" +
                "insert into gerp_teast set content = \"你是年少的欢喜，倒过来念。\";\n" +
                "insert into gerp_teast set content = \"自从你走了，总有人问我为什么发呆。'\";\n" +
                "insert into gerp_teast set content = \"我觉得我们真的不适合当情人，你愿意当我老婆吗?\";\n" +
                "insert into gerp_teast set content = \"我的抱枕坏了，又没钱买新的\";\n" +
                "insert into gerp_teast set content = \"今天天气好，好适合结婚\";\n" +
                "insert into gerp_teast set content = \"你可以笑一下吗?我的咖啡忘记加糖了。\";\n" +
                "insert into gerp_teast set content = \"你只是随便穿个衬衣牛仔裤，都不用对我勾手放电，只要往那儿一站，就已经撩我于无形。'\";\n" +
                "insert into gerp_teast set content = \"我送你支口红你每天还我一点\";\n" +
                "insert into gerp_teast set content = \"愿意跟我体验一下不单身的感觉吗\";\n" +
                "insert into gerp_teast set content = \"相约而坐，相对无言。　　\";\n" +
                "insert into gerp_teast set content = \"我说，在看不到你的时候，就是我最寂寞的时候。　　\";\n" +
                "insert into gerp_teast set content = \"下辈子我们还在一起，你不来，我不老。　　\";\n" +
                "insert into gerp_teast set content = \"有一种终生配偶制的两栖动物叫松果蜥。　　\";\n" +
                "insert into gerp_teast set content = \"喜欢是乍见之欢，爱是久处不厌。　　\";\n" +
                "insert into gerp_teast set content = \"万千繁华不复你笑靥如花，似水流年。　　\";\n" +
                "insert into gerp_teast set content = \"在所有过去与将来，所有怀念和值得期待的景色里，我只喜欢你。　　\";\n" +
                "insert into gerp_teast set content = \"如果哪天我想环游世界了，我可以围着你转一圈吗？　　\";\n" +
                "insert into gerp_teast set content = \"能不能把我们的革命友谊再升华一下。　　\";\n" +
                "insert into gerp_teast set content = \"你的名字只有两个字，虽构不成一句话，但已经装满了我的心。　　\";\n" +
                "insert into gerp_teast set content = \"因为你，每天都是情人节。　　\";\n" +
                "insert into gerp_teast set content = \"我爱你，非常非常爱。很多年后我对很多人说过这句话，却再没有后面那五个字。　　\";\n" +
                "insert into gerp_teast set content = \"妹子，帮个忙，我爸妈想要个儿媳妇！　　\";\n" +
                "insert into gerp_teast set content = \"等我一下，我先洗个头再爱你。　　\";\n" +
                "insert into gerp_teast set content = \"如她伤你心，如她说别离，如果未嫌弃，我即奔向你。　　\";\n" +
                "insert into gerp_teast set content = \"右手敬礼，左手牵你。　　\";\n" +
                "insert into gerp_teast set content = \"别人眼中恶魔的你，却是我心中的天使。　　\";\n" +
                "insert into gerp_teast set content = \"我想要的很简单，你在，我在，时光还在。　　\";\n" +
                "insert into gerp_teast set content = \"山是水的故事，云是风的故事，你是我的故事。　　\";\n" +
                "insert into gerp_teast set content = \"遐想今日温柔，温柔于日后遐想：风雨执手，蹒跚而行。　　\";\n" +
                "insert into gerp_teast set content = \"愿意我开飞机送你一程吗？　　\";\n" +
                "insert into gerp_teast set content = \"就这样爱上了一首歌，一遍遍循环，听着歌词间的你我，傻笑着《情非得已》。　　\";\n" +
                "insert into gerp_teast set content = \"你是我命中的---在劫难逃。　　\";\n" +
                "insert into gerp_teast set content = \"我不喜欢这世界，我只喜欢你，喜欢有你的世界。　　\";\n" +
                "insert into gerp_teast set content = \"只有自己跟自己过得太久了的人才会渴望爱情，也才有资格获得爱情。　　\";\n" +
                "insert into gerp_teast set content = \"终有一天你我的距离将为负。　　\";\n" +
                "insert into gerp_teast set content = \"想象你，想像你，想你。　　\";\n" +
                "insert into gerp_teast set content = \"我愿意守护你所有的孤独。　　\";\n" +
                "insert into gerp_teast set content = \"只有和你在一起的时候，才不会去羡慕别人。　　\";\n" +
                "insert into gerp_teast set content = \"你怕，我怕，我还没说怕什么呢，关于你的所有，我都怕。　　\";\n" +
                "insert into gerp_teast set content = \"与你相遇，如入梦中，从此不愿醒矣。　　\";\n" +
                "insert into gerp_teast set content = \"校园卡给你，随便刷（总裁脸）。　　\";\n" +
                "insert into gerp_teast set content = \"选好化妆水乳液隔离霜眉粉口红眼线笔卧蚕笔以后，给你化好陪我出去吃饭吧！　　\";\n" +
                "insert into gerp_teast set content = \"点分，故意找你，只是没说出那句，其实我想你。　　\";\n" +
                "insert into gerp_teast set content = \"你还想要一个妈妈嘛，我把我的妈妈分给你。　　\";\n" +
                "insert into gerp_teast set content = \"你这么针对我，是不是想睡我。　　\";\n" +
                "insert into gerp_teast set content = \"我喜欢矮穷矬，矮了我可以低头，穷了我可以养他，矬的话可以对我一心一意。　　\";\n" +
                "insert into gerp_teast set content = \"来到人世间蹉跎几十年，只为望你回眸一眼。　　\";\n" +
                "insert into gerp_teast set content = \"你有地图吗，我在你的眼睛里迷路了。　　\";\n" +
                "insert into gerp_teast set content = \"我以为开学前见你一面，到学校后就不会想你。　　\";\n" +
                "insert into gerp_teast set content = \"你还小，我不忍心跟你谈恋爱。　　\";\n" +
                "insert into gerp_teast set content = \"我希望在我们以后的生活中都因为拥有彼此而快乐无边。　　\";\n" +
                "insert into gerp_teast set content = \"我每天偷拍你一張照片，等到妳歲的時候，我再一張張翻開給你看。　　\";\n" +
                "insert into gerp_teast set content = \"你别哭，哭了我想笑。　　\";\n" +
                "insert into gerp_teast set content = \"流动在阳光和虚无间的我爱瑶。　　\";\n" +
                "insert into gerp_teast set content = \"从你的世界路过，我是那个偷影子的人。虽然无声告白，只愿你让我留在你身边。　　\";\n" +
                "insert into gerp_teast set content = \"以后我在楼下等你的时候你要快点，你们宿舍楼前的梧桐树都被我抠的没皮了。　　\";\n" +
                "insert into gerp_teast set content = \"你正在阅读我想你的声音。　　\";\n" +
                "insert into gerp_teast set content = \"我单身，自信帅，就酱紫。　　\";\n" +
                "insert into gerp_teast set content = \"我讨厌一切让我上瘾的东西除了你。　　\";\n" +
                "insert into gerp_teast set content = \"我送你一支口红，你要每天还我一点。　　\";\n" +
                "insert into gerp_teast set content = \"以后想在哪儿工作？……让我想想哈……在有你的地方。　　\";\n" +
                "insert into gerp_teast set content = \"说不喜欢你都是四月的谎言。　　\";\n" +
                "insert into gerp_teast set content = \"对不起，我明知道会这样 ，还是忍不住靠近你。　　\";\n" +
                "insert into gerp_teast set content = \"巧哎，看到这个比赛就想到你了。　　\";\n" +
                "insert into gerp_teast set content = \"微博有什么好玩的？哪有我好玩？　　\";\n" +
                "insert into gerp_teast set content = \"我以为开学前见你一面，回到学校的时候就不会再想你……　　\";\n" +
                "insert into gerp_teast set content = \"至少现在，你过得很好，这就够了。　　\";\n" +
                "insert into gerp_teast set content = \"爱情是没有国界的哈。　　\";\n" +
                "insert into gerp_teast set content = \"你总是能让我带着每天的晚安把梦做到最感动。　　\";\n" +
                "insert into gerp_teast set content = \"风这么大要多出门。万一吹到美女怀里，像我这样不要脸，肯定是赖着不动的。　　\";\n" +
                "insert into gerp_teast set content = \"停止思念，从来没有，一刻也没有。　　\";\n" +
                "insert into gerp_teast set content = \"所爱隔山海，山海不可平。　　\";\n" +
                "insert into gerp_teast set content = \"异地算什么，之前四年都过来了，还怕这四年？　　\";\n" +
                "insert into gerp_teast set content = \"小心翼翼地拉着你的手，在心里早就和你过完了一生。　　\";\n" +
                "insert into gerp_teast set content = \"你存在的本身，便是我的神迹。　　\";\n" +
                "insert into gerp_teast set content = \"Love=you +me+future children.　　\";\n" +
                "insert into gerp_teast set content = \"不许动，打劫，把你的心给我。　　\";\n" +
                "insert into gerp_teast set content = \"男：我已经完成领略世界风采的梦想。女：为什么？男：因为你就是我的世界。　　\";\n" +
                "insert into gerp_teast set content = \"我如今的气质里，藏着你走过的路，放着你唱过的歌，还有我深深喜欢着的你。　　\";\n" +
                "insert into gerp_teast set content = \"雪花来了，我的心还空着，你来吗？　　\";\n" +
                "insert into gerp_teast set content = \"与你相见，是我最美的相遇。　　\";\n" +
                "insert into gerp_teast set content = \"在春风起时你来到我的身边，我们一起度过人生的每一个季节。　　\";\n" +
                "insert into gerp_teast set content = \"我想和你虚度时光。　　\";\n" +
                "insert into gerp_teast set content = \"如果哪一天我想环游世界了，我可以围着你转一圈吗？\";\n" +
                "insert into gerp_teast set content = \"我想要的很简单，时光还在，你还在。\";\n" +
                "insert into gerp_teast set content = \"想和你喝酒是假，想醉你怀里是真。\";\n" +
                "insert into gerp_teast set content = \"傻笑不是与生俱来的，而是由我爱上你的那一刻开始的。\";\n" +
                "insert into gerp_teast set content = \"你这么针对我，是不是想睡我。\";\n" +
                "insert into gerp_teast set content = \"假如你是一棵仙人掌，我也愿意忍受所有的疼痛来抱着你。\";\n" +
                "insert into gerp_teast set content = \"假如可以的话，我愿意花去生命中的每一分每一秒，陪着你。\";\n" +
                "insert into gerp_teast set content = \"你是年少的欢喜，我想把这句话反过来告诉你。\";\n" +
                "insert into gerp_teast set content = \"你还想要一个妈妈嘛，我把我的妈妈分给你。\";\n" +
                "insert into gerp_teast set content = \"谢谢你的微笑，曾经慌乱过我的年华。\";\n" +
                "insert into gerp_teast set content = \"等我一下，我先洗个头再爱你。\";\n" +
                "insert into gerp_teast set content = \"异地算什么，之前四年都过来了，还怕这四年?\";\n" +
                "insert into gerp_teast set content = \"我和我的猫都很想你，可是我没有猫，也没有你。\";\n" +
                "insert into gerp_teast set content = \"你知道我最珍惜什么吗，就是这句话的第一个字。\";\n" +
                "insert into gerp_teast set content = \"我仿佛从不懂什么是爱，直到，我遇见你。\";\n" +
                "insert into gerp_teast set content = \"我明白你会来，所以我等。\";\n" +
                "insert into gerp_teast set content = \"听过一个故事没有?弓在箭射出之前低声对箭说：你的自由是我的。\";\n" +
                "insert into gerp_teast set content = \"妹子，帮个忙，我爸妈想要个儿媳妇!\";\n" +
                "insert into gerp_teast set content = \"幸福的秘诀是得到自由，而自由的秘诀是勇气。\";\n" +
                "insert into gerp_teast set content = \"我都舍不得欺负的人，哪能让别人欺负?\";\n" +
                "insert into gerp_teast set content = \"看着微笑的你，突然发现，我真是世界上最幸福的人。\";\n" +
                "insert into gerp_teast set content = \"你的名字只有两个字，虽构不成一句话，但已经装满了我的心。\";\n" +
                "insert into gerp_teast set content = \"你烦我，你再烦我，你就娶我。\";\n" +
                "insert into gerp_teast set content = \"人生不长，该珍惜就别保持不近不远，我只想再抱你紧一点。\";\n" +
                "insert into gerp_teast set content = \"只有自己跟自己过得太久了的人才会渴望爱情，也才有资格获得爱情。\";\n" +
                "insert into gerp_teast set content = \"你别难过，风筝有风，海豚有海，你还有我。\";\n" +
                "insert into gerp_teast set content = \"看过怦然心动吗?所以你懂我对你感觉?怦然心动。\";\n" +
                "insert into gerp_teast set content = \"雪花来了，我的心还空着，你来吗?\";\n" +
                "insert into gerp_teast set content = \"你在的时候，你是一切;你不在的时候，一切是你!\";\n" +
                "insert into gerp_teast set content = \"我可能缺席了你的过去，但我希望你不要缺席我的未来。\";\n" +
                "insert into gerp_teast set content = \"你还小，我不忍心跟你谈恋爱。\";\n" +
                "insert into gerp_teast set content = \"再累，再苦，再疼，也只是为了你能喜欢我而已。\";\n" +
                "insert into gerp_teast set content = \"世界上最温暖的两个字是从你口中说出的晚安。\";\n" +
                "insert into gerp_teast set content = \"没有你的生活如同行尸走肉般，一根烟，一杯酒，就这么无所谓下去。\";\n" +
                "insert into gerp_teast set content = \"如果你愿意，我就喜欢你，如果你不愿意，我就单相思，你愿意吗?\";\n" +
                "insert into gerp_teast set content = \"不是除了你，我就没人要了。只是除了你，我谁都不想要。\";\n" +
                "insert into gerp_teast set content = \"世上最浪漫和最自私的话就是：你是我一个人的。\";\n" +
                "insert into gerp_teast set content = \"如她伤你心，如她说别离，如果未嫌弃，我即奔向你。\";\n" +
                "insert into gerp_teast set content = \"给你讲个故事，这故事很长，所以我长话短说，我想你了。\";\n" +
                "insert into gerp_teast set content = \"能不能把我们的革命友谊再升华一下。\";\n" +
                "insert into gerp_teast set content = \"奇迹就留给别人吧，我有你了。\";\n" +
                "insert into gerp_teast set content = \"我以为开学前见你一面，到学校后就不会想你。\";\n" +
                "insert into gerp_teast set content = \"我希望在我们以后的生活中都因为拥有彼此而快乐无边。\";\n" +
                "insert into gerp_teast set content = \"下辈子我们还在一起，你不来，我不老。\";\n" +
                "insert into gerp_teast set content = \"你怕，我怕，我还没说怕什么呢，关于你的所有，我都怕。\";\n" +
                "insert into gerp_teast set content = \"与你相遇，如入梦中，从此不愿醒矣。\";\n" +
                "insert into gerp_teast set content = \"你的前半生没有我，那么就让我陪你走完后半生。\";\n" +
                "insert into gerp_teast set content = \"在认识你之后，我才发现自己可以这样情愿的付出。\";\n" +
                "insert into gerp_teast set content = \"不管你在乎不在乎我，我依旧会在乎你。\";\n" +
                "insert into gerp_teast set content = \"这世界上一共三种人，坏人，人妖，我的人。\";\n" +
                "insert into gerp_teast set content = \"遇见你，是我最美丽的意外。\";\n" +
                "insert into gerp_teast set content = \"如果哪一天我想环游世界了，我可以围着你转一圈吗?\";\n" +
                "insert into gerp_teast set content = \"我只是喜欢你，我没有恶意。\";\n" +
                "insert into gerp_teast set content = \"我的世界不允许你的消失，不管结局是否完美。\";\n" +
                "insert into gerp_teast set content = \"我不喜欢这世界，我只喜欢你，喜欢有你的世界。\";\n" +
                "insert into gerp_teast set content = \"Hey!我有大白兔，你愿不愿做我的英雄?\";\n" +
                "insert into gerp_teast set content = \"请你从我梦里出去，或者，再也不要离开。\";\n" +
                "insert into gerp_teast set content = \"没什么特别的事，只想听听你的声音。\";\n" +
                "insert into gerp_teast set content = \"牵着我的手，闭着眼睛走你也不会迷路。\";\n" +
                "insert into gerp_teast set content = \"我想你一定很忙，所以你只看前三个字就好。\";\n" +
                "insert into gerp_teast set content = \"与你相见，是我最美的相遇。\";\n" +
                "insert into gerp_teast set content = \"我这么喜欢吃伊利巧乐兹，只因为那句喜欢你，没道理。\";\n" +
                "insert into gerp_teast set content = \"我真的很花心，喜欢每一天的你和每一个的你。\";\n" +
                "insert into gerp_teast set content = \"你是我的今天，以及所有的明天。\";\n" +
                "insert into gerp_teast set content = \"我说，在看不到你的时候，就是我最寂寞的时候。\";\n" +
                "insert into gerp_teast set content = \"我的运气只到遇见你，接下来的，就要自己努力了。\";\n" +
                "insert into gerp_teast set content = \"我有几千万里的山光相与你说，这沿途的星辰也想粒粒分明摘取下来交由你，你可不可以等我。\";\n" +
                "insert into gerp_teast set content = \"如果你过得不幸福，我所做的一切才是徒劳。\";\n" +
                "insert into gerp_teast set content = \"你为什么那么喜欢落日？'因为它像极了我喜欢你的心……'嗯？'就算会一点一点沉下去，明天照样会升起。'\";\n" +
                "insert into gerp_teast set content = \"我为的是我的心。\";\n" +
                "insert into gerp_teast set content = \"有一句话，我只问一次，以后都不会再问了，为什么会是我？'答案很长，我准备用一生来回答，你准备好要听了吗？'\";\n" +
                "insert into gerp_teast set content = \"在遇到她之前，我从未想过要结婚。和她在一起这么多年，我也从未想过娶别的女人。\";\n" +
                "insert into gerp_teast set content = \"你站在桥上看风景，看风景的人在桥上看你。明月装饰了你的窗子，你却装饰了别人的梦。\";\n" +
                "insert into gerp_teast set content = \"我寄你的信，总要送往邮局，不喜欢放在街边的绿色邮筒中，我总疑心那里会慢一点。\";\n" +
                "insert into gerp_teast set content = \"珍簟凉风著，瑶琴寄恨生。嵇君懒书札，底物慰秋情。\";\n" +
                "insert into gerp_teast set content = \"言与司合,安上已脱,芝芙草拔。\";\n" +
                "insert into gerp_teast set content = \"你会不爱我吗？'不爱你？不会。爱你就像爱生命。'\";\n" +
                "insert into gerp_teast set content = \"春水初生，春林初盛，春风十里，不如你。\";\n" +
                "insert into gerp_teast set content = \"我实在喜欢你那一身诗劲，我爱你像爱一首诗一样。\";\n" +
                "insert into gerp_teast set content = \"我愿意舍弃一切，以想念你终此一生。\";\n" +
                "insert into gerp_teast set content = \"静下来想你，觉得一切都美好得不可思议。\";\n" +
                "insert into gerp_teast set content = \"你不在手边，手一直想你。\";\n" +
                "insert into gerp_teast set content = \"风和日暖，令人愿意永远活下去。\";\n" +
                "insert into gerp_teast set content = \"今天起来看见太阳光，心里有一点高兴。\";\n" +
                "insert into gerp_teast set content = \"后海有树的院子，夏代有工的玉，此时此刻的云，二十来岁的你。\";\n" +
                "insert into gerp_teast set content = \"我爱他，是因为他像爱情本身该有的样子。\";\n" +
                "insert into gerp_teast set content = \"你问我爱你值不值得，其实你应该知道，爱就是不问值不值得。\";\n" +
                "insert into gerp_teast set content = \"我要用尽我的万种风情，让你将来任何不和我在一起的时候，内心都无法安宁。\";\n" +
                "insert into gerp_teast set content = \"好多年了，你一直在我的伤口幽居。我放下过天地，从未放下过你。\";\n" +
                "insert into gerp_teast set content = \"我这辈子走过很多的路，行过很多地方的桥，看过很多次数的云，喝过很多种类的酒，却只爱过一个正当年龄的人。\";\n" +
                "insert into gerp_teast set content = \"从前日色变得慢，车，马，邮件都慢。一生只够爱一个人。\";\n" +
                "insert into gerp_teast set content = \"你再不来，我要下雪了。\";\n" +
                "insert into gerp_teast set content = \"海底月是天上月，眼前人是心上人。向来心是看客心，奈何人是剧中人。\";\n" +
                "insert into gerp_teast set content = \"你以为我刀枪不入，我以为你百毒不侵。\";\n" +
                "insert into gerp_teast set content = \"为你，千千万万遍。\";\n" +
                "insert into gerp_teast set content = \"醒来觉得甚是爱你。\";\n" +
                "insert into gerp_teast set content = \"我遇见你，我记得你，这座城市天生就适合谈恋爱，你天生就适合我的灵魂。\";\n" +
                "insert into gerp_teast set content = \"你眉目笑语使我病了一场，热势退尽，还我寂寞的健康。\";\n" +
                "insert into gerp_teast set content = \"若深情不能对等，愿爱得更多的人是我。\";\n" +
                "insert into gerp_teast set content = \"自从我们相遇，你是我白天黑夜不落的星。\";\n" +
                "insert into gerp_teast set content =\"我一天一天明白你的平凡，同时却一天一天愈更加深切地爱你。你如照镜子，你不会我看得见你特别美好的所在，但是你如走到我的心里来时，你一定能知道自己是怎样好法。\";\n" +
                "insert into gerp_teast set content = \"在我贫瘠的土地上你是我最后的玫瑰。\";\n" +
                "insert into gerp_teast set content = \"草在结它的种子，风在摇它的叶子，我们站着不说话，就十分美好。城\";\n" +
                "insert into gerp_teast set content = \"我的心是旷野的鸟，在你的眼里找到了天空。\";\n" +
                "insert into gerp_teast set content = \"在青山绿水之间，我想牵你的手，走过这座桥，桥上是绿叶红花，桥下是流水人家，桥的那头是青丝，桥的这头是白发。\";\n" +
                "insert into gerp_teast set content = \"月亮照回湖心，野鹤奔向闲云，我步入你。\";\n" +
                "insert into gerp_teast set content = \"我住长江头，君住长江尾，日日思君不见君，共饮长江水。此水几时休，此恨几时已。只愿君心似我心，定不负相思意。\";\n" +
                "insert into gerp_teast set content = \"我把我的整个灵魂都给你，连同它的怪癖，耍小脾气，忽明忽暗，一千八百种坏毛病。它真讨厌，只有一点好，爱你。\";\n" +
                "insert into gerp_teast set content = \"因为你，我愿意成为一个更好的人，不想成为你的包袱，因此发奋努力，只是为了想要证明我足以与你相配。\";\n" +
                "insert into gerp_teast set content = \"你的过去我不愿过问，那是你的事情。你的未来我希望我能参与，那是我的荣幸。\";\n" +
                "insert into gerp_teast set content = \"我只有一点点的坏，小小的坏而已，最近我连柿子都没有偷了。上次经过好大一片橘子林，我好想偷几个，一想到你不喜欢，我连一个都没有摘呢。\";\n" +
                "insert into gerp_teast set content = \"世界上有那么多城镇，城镇中有那么多酒馆，他却走进了我的。\";\n" +
                "insert into gerp_teast set content = \"我，等着你。相信有一天你会出现抚摸我的头，夸奖我。时间流逝，我在守着爱你的那份忠诚。\";\n" +
                "insert into gerp_teast set content = \"是你让我一直远离那无际的深渊。\";\n" +
                "insert into gerp_teast set content = \"刚刚好，看见你幸福的样子，于是幸福着你的幸福。\";\n" +
                "insert into gerp_teast set content = \"若深情不能对等，愿爱得更多的人是我。If equal affection cannot be,let the more loving one be me\";\n" +
                "insert into gerp_teast set content = \"与君初相识，犹似故人归。天涯明月新，朝暮最相思。我曾踏月来，只因你在山中。\";\n" +
                "insert into gerp_teast set content = \"南有乔木，不可休思，汉有游女，不可求思。\";\n" +
                "insert into gerp_teast set content = \"我是如此的拙于表达，我所经历的时间和万物，真正算作美好的——并不多，所以才会对你如此珍而重之。今夜我不关心人类，我只想你。\";\n" +
                "insert into gerp_teast set content = \"其实你不喜欢我，我也不会死。但是如果你肯喜欢我，我一定会非常非常勇敢的活下去。\";";
        String replace = str.replace("　　", "");
        return replace;
    }

}
